-- SWITCH TO THE CORRECT DATABASE
USE alx_book_store;

-- FULL DESCRIPTION OF THE BOOKS TABLE WITHOUT DESCRIBE OR ANALYZE
SELECT
  COLUMN_NAME AS Field,
  COLUMN_TYPE AS Type,
  IS_NULLABLE AS 'Null',
  COLUMN_KEY AS 'Key',
  COLUMN_DEFAULT AS 'Default',
  EXTRA AS Extra
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = DATABASE()
  AND TABLE_NAME = 'Books'
ORDER BY ORDINAL_POSITION;
