-- SWITCH TO THE CORRECT DATABASE
USE alx_book_store;

-- PRINT A DESCRIBE-LIKE VIEW OF THE `books` TABLE WITHOUT USING DESCRIBE/EXPLAIN
SELECT
  COLUMN_NAME AS `Field`,
  COLUMN_TYPE AS `Type`,
  IF(IS_NULLABLE = 'YES', 'YES', 'NO') AS `Null`,
  CASE
    WHEN COLUMN_KEY = 'PRI' THEN 'PRI'
    WHEN COLUMN_KEY = 'UNI' THEN 'UNI'
    WHEN COLUMN_KEY = 'MUL' THEN 'MUL'
    ELSE ''
  END AS `Key`,
  COLUMN_DEFAULT AS `Default`,
  EXTRA AS `Extra`
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = DATABASE()
  AND TABLE_NAME IN ('books', 'Books')
ORDER BY ORDINAL_POSITION;
